[production]
# One config file may contain multiple named sections providing multiple configuration environments.

# index_driver is optional and defaults to "default" (the default Postgres index driver)
index_driver: default

# The remaining configuration entries are for the default Postgres index driver and
# may not apply to other index drivers.
db_database: datacube

# A blank host will use a local socket. Specify a hostname (such as localhost) to use TCP.
db_hostname:

# Port is optional. The default port is 5432.
# db_port:

# Credentials are optional: you might have other Postgres authentication configured.
# The default username otherwise is the current user id.
db_username: ubuntu
db_password: pass

[default]
# The section named "default" (or "datacube") is used if no environment is specified.
#
# An environment may be declared as an alias to another environment.
# This section sets ``default`` as an alias to the ``production`` environment, ensuring that
# the ``production`` environment will be used if no environment is specified.
# No other configuration values may be used in an ``alias`` environment.
alias: production

[test]
# A "test" environment that accesses a separate test database.
index_driver: default
db_database: datacube_test

[migration]
# An environment using the new postgis index driver
index_driver: postgis
# For both the postgis and postgres index drivers, database connection details may be configured in a single
# db_url config entry, instead of the db_username, db_database, db_password, etc.
db_url: postgresql://username:password@server.domain:5444/mydb

[null]
# A "null" environment for working with no index.
index_driver: null

[local_memory]
# A local non-persistent in-memory index.
#   Compatible with the default index driver, but resides purely in memory with no persistent database.
#   Note that each new invocation will receive a new, empty index.
index_driver: memory