- name: Initialize RasDaMan SUT
  hosts: rasdaman_sut
  become: true
  tasks:
    - name: Copy setup scripts to remote
      copy:
        src: ../../rasdaman/sut/
        dest: /setup/
        mode: '0755'

    - name: Execute init.sh
      shell: /setup/init.sh

    - name: Execute dwd-import.sh
      shell: /setup/dwd-import.sh